const DEFAULT_SCHEDULE = [
  [1,'09:50','2Г','Шахматы'],[1,'10:50','4В','Информатика'],[1,'11:40','5А','Информатика'],[1,'12:40','4А','Шахматы'],[1,'16:10','2А','Шахматы'],
  [2,'10:50','5Г','Информатика'],[2,'11:40','2В','Шахматы'],[2,'12:40','4Б','Шахматы'],[2,'13:40','1Б','Шахматы'],
  [3,'10:50','4Г','Шахматы'],[3,'11:40','1В','Шахматы'],[3,'12:40','1А','Шахматы'],
  [4,'08:50','6Б','Информатика'],[4,'10:50','5Б','Информатика'],[4,'11:40','6А','Информатика'],[4,'12:40','4Б','Информатика'],[4,'16:10','2Б','Шахматы'],
  [5,'08:00','6В','Информатика'],[5,'08:50','4Г','Информатика'],[5,'09:50','5В','Информатика'],[5,'10:50','6Г','Информатика'],[5,'11:40','4В','Шахматы'],[5,'12:40','4А','Информатика']
].map((x,i)=>({id:`s${i+1}`,day:x[0],time:x[1],className:x[2],subject:x[3]}));
const dayNames=['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'];
const monthNames=['январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь'];
const SUPABASE_URL = 'https://bxvnynbrzzwdvyyazmfp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_MwTZaiT3_Qu1Kqoe83r93A_Bv6xpD1U';
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

let schedule=[], records=[], selectedDate=new Date(), view='journal', currentUser=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function localRead(key, fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function localSave(){localStorage.setItem('dolich-schedule',JSON.stringify(schedule));localStorage.setItem('dolich-records',JSON.stringify(records))}
function toDbLesson(r){return {id:r.id,schedule_id:r.scheduleId||null,user_id:currentUser.id,date:r.date,time:r.time,class_name:r.className,subject:r.subject,status:r.status,topic:r.topic||'',homework:r.homework||'',notes:r.notes||'',assessment:!!r.assessment}}
function fromDbLesson(r){return {id:r.id,scheduleId:r.schedule_id||'',date:r.date,time:r.time,className:r.class_name,subject:r.subject,status:r.status,topic:r.topic||'',homework:r.homework||'',notes:r.notes||'',assessment:!!r.assessment}}
function toDbSchedule(s){return {id:s.id,user_id:currentUser.id,day:s.day,time:s.time,class_name:s.className,subject:s.subject}}
function fromDbSchedule(s){return {id:s.id,day:s.day,time:s.time,className:s.class_name,subject:s.subject}}
async function loadCloudData(){
  const [{data:dbSchedule,error:sErr},{data:dbRecords,error:rErr}]=await Promise.all([supabaseClient.from('schedule').select('*').order('day').order('time'),supabaseClient.from('lessons').select('*').order('date').order('time')]);
  if(sErr) throw sErr; if(rErr) throw rErr;
  if((dbSchedule||[]).length===0){const localSchedule=localRead('dolich-schedule',DEFAULT_SCHEDULE);const payload=localSchedule.map(toDbSchedule);if(payload.length){const {data,error}=await supabaseClient.from('schedule').insert(payload).select('*');if(error) throw error;schedule=(data||[]).map(fromDbSchedule)}else schedule=[]}else schedule=(dbSchedule||[]).map(fromDbSchedule);
  records=(dbRecords||[]).map(fromDbLesson);localSave();
}
async function saveLessonCloud(r){const {error}=await supabaseClient.from('lessons').upsert(toDbLesson(r));if(error) throw error}
async function saveScheduleCloud(s){const {error}=await supabaseClient.from('schedule').upsert(toDbSchedule(s));if(error) throw error}
async function deleteScheduleCloud(id){const {error}=await supabaseClient.from('schedule').delete().eq('id',id).eq('user_id',currentUser.id);if(error) throw error}
function iso(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function parseDate(s){return new Date(`${s}T12:00:00`)}
function dayKey(d){return d.getDay()}
function displayDate(d){return `${dayNames[d.getDay()]}, ${d.getDate()} ${monthNames[d.getMonth()]} ${d.getFullYear()}`}
function uid(){return `r${Date.now()}${Math.random().toString(16).slice(2)}`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2300)}
function statusName(s){return {done:'Проведён','not-done':'Не проведён',moved:'Перенесён',pending:'Ожидает отчёта'}[s]}
function getRecord(date, item){return records.find(r=>r.date===date&&r.scheduleId===item.id)||null}
function lessonsForDate(d){let date=iso(d), base=schedule.filter(x=>x.day===dayKey(d)).map(s=>{let r=getRecord(date,s);return r?{...s,...r}:{...s,date,status:'pending',topic:'',homework:'',notes:'',assessment:false}});return [...base,...records.filter(r=>r.date===date&&!r.scheduleId)].sort((a,b)=>a.time.localeCompare(b.time))}
function render(){renderNav();renderJournal();renderWeek();renderMonth();renderSchedule();renderClassOptions()}
function renderNav(){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`${view}View`));$$('.view').forEach(x=>x.style.display=x.classList.contains('active')?'block':'none');$('#viewTitle').textContent={journal:'Журнал уроков',week:'Недельный обзор',month:'Месячный обзор',schedule:'Расписание'}[view]}
function renderClassOptions(){let selected=$('#classFilter').value,classes=[...new Set(schedule.map(s=>s.className))].sort();$('#classFilter').innerHTML='<option value="">Все классы</option>'+classes.map(c=>`<option ${c===selected?'selected':''}>${c}</option>`).join('')}
function renderJournal(){let d=selectedDate, lessons=lessonsForDate(d), search=$('#searchInput').value.toLowerCase(), cf=$('#classFilter').value,sf=$('#subjectFilter').value,st=$('#statusFilter').value;$('#datePicker').value=iso(d);$('#dateHeading').textContent=displayDate(d);let filtered=lessons.filter(x=>(!cf||x.className===cf)&&(!sf||x.subject===sf)&&(!st||x.status===st)&&(!search||`${x.topic} ${x.notes} ${x.homework}`.toLowerCase().includes(search)));$('#lessonsList').innerHTML=filtered.map(x=>`<article class="lesson-row"><div class="lesson-time">${x.time}<small>до ${plus40(x.time)}</small></div><div class="lesson-main"><span class="class-tag">${x.className}</span><span class="subject">${x.subject}</span>${x.assessment?'<span class="assessment">оценивание</span>':''}</div><div class="topic">${x.topic||'Тема пока не указана'}</div><div class="row-actions"><select class="status-select ${x.status}" data-id="${x.id||''}" data-schedule="${x.scheduleId||x.id}" aria-label="Статус урока">${['pending','done','not-done','moved'].map(s=>`<option value="${s}" ${x.status===s?'selected':''}>${statusName(s)}</option>`).join('')}</select><button class="edit-link" data-edit="${x.id||''}" data-schedule="${x.scheduleId||x.id}">Открыть</button></div></article>`).join('');$('#emptyState').hidden=filtered.length>0;let period=records.filter(r=>r.date===iso(d));let total=lessons.length,done=lessons.filter(l=>l.status==='done').length,pending=lessons.filter(l=>l.status==='pending').length,missed=lessons.filter(l=>l.status==='not-done').length;$('#doneCount').textContent=done;$('#pendingCount').textContent=pending;$('#missedCount').textContent=missed;$('#totalCount').textContent=total;$('#doneHint').textContent=total?'за выбранный день':'нет уроков';$('#pendingHint').textContent=total?'по расписанию':'по расписанию';$('#totalHint').textContent='за выбранный день';}
function plus40(t){let [h,m]=t.split(':').map(Number);m+=40;return `${String(h+Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function monday(d){let x=new Date(d);let offset=(x.getDay()+6)%7;x.setDate(x.getDate()-offset);return x}
function renderWeek(){let start=monday(selectedDate),days=[0,1,2,3,4].map(i=>{let x=new Date(start);x.setDate(start.getDate()+i);return x});$('#weekRange').textContent=`${days[0].getDate()} ${monthNames[days[0].getMonth()]} — ${days[4].getDate()} ${monthNames[days[4].getMonth()]}`;$('#weekGrid').innerHTML=days.map(d=>`<section class="week-day"><header><strong>${dayNames[d.getDay()]}</strong><small>${d.getDate()} ${monthNames[d.getMonth()]}</small></header>${lessonsForDate(d).map(l=>`<div class="mini-lesson" data-open-date="${iso(d)}" data-open-schedule="${l.scheduleId||l.id}"><time>${l.time}</time><span>${l.className} · ${l.subject}</span><small class="mini-status ${l.status}">${statusName(l.status)}</small></div>`).join('')||'<div class="mini-lesson">Уроков нет</div>'}</section>`).join('')}
function monthRecords(year,month){return records.filter(r=>{let d=parseDate(r.date);return d.getFullYear()===year&&d.getMonth()===month})}
function renderMonth(){let y=selectedDate.getFullYear(),m=selectedDate.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();$('#monthLabel').textContent=`${monthNames[m][0].toUpperCase()+monthNames[m].slice(1)} ${y}`;let cells=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="weekday">${x}</div>`);for(let i=0;i<start;i++)cells.push('<div class="cal-day empty"></div>');for(let n=1;n<=days;n++){let d=new Date(y,m,n),ls=lessonsForDate(d);cells.push(`<button class="cal-day ${iso(d)===iso(selectedDate)?'selected':''}" data-cal-date="${iso(d)}"><span class="num">${n}</span><div class="dots">${ls.slice(0,6).map(l=>`<i class="dot ${l.status}"></i>`).join('')}</div></button>`)}$('#calendar').innerHTML=`<div class="calendar-grid">${cells.join('')}</div>`;let all=[];for(let n=1;n<=days;n++)all.push(...lessonsForDate(new Date(y,m,n)));let count=s=>all.filter(x=>x.status===s).length, done=count('done'),total=all.length;$('#monthStats').innerHTML=[['Проведено',done,'green'],['Ожидают отчёта',count('pending'),'orange'],['Не проведено',count('not-done'),'red'],['Перенесено',count('moved'),'blue']].map(x=>`<div class="summary-line"><span>${x[0]}</span><strong class="${x[2]}">${x[1]}</strong></div>`).join('');let subjects=['Информатика','Шахматы'];$('#subjectStats').innerHTML=subjects.map(s=>{let a=all.filter(l=>l.subject===s),d=a.filter(l=>l.status==='done').length,p=a.length?Math.round(100*d/a.length):0;return `<div class="progress-line"><div><span>${s}</span><strong>${d}/${a.length}</strong></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('')}
function renderSchedule(){let cols=[1,2,3,4,5];$('#scheduleGrid').innerHTML=cols.map(day=>`<section class="schedule-day"><header><strong>${dayNames[day]}</strong><span>${schedule.filter(s=>s.day===day).length} ур.</span></header>${schedule.filter(s=>s.day===day).sort((a,b)=>a.time.localeCompare(b.time)).map(s=>`<div class="schedule-item"><time>${s.time}</time><div>${s.className}<small>${s.subject}</small></div><button data-schedule-edit="${s.id}" title="Редактировать">⋯</button></div>`).join('')}</section>`).join('')}
function openLesson(recordId,scheduleId,date=iso(selectedDate)){let source=recordId?records.find(r=>r.id===recordId):null;if(!source&&scheduleId){let sched=schedule.find(s=>s.id===scheduleId);source=getRecord(date,sched)||{...sched,date,status:'pending'}}source=source||{date,time:'',className:'',subject:'Информатика',status:'pending',topic:'',homework:'',notes:'',assessment:false};$('#recordId').value=source.id||'';$('#formDate').value=source.date;$('#formTime').value=source.time;$('#formClass').value=source.className;$('#formSubject').value=source.subject;$('#formStatus').value=source.status;$('#formTopic').value=source.topic||'';$('#formHomework').value=source.homework||'';$('#formNotes').value=source.notes||'';$('#formAssessment').checked=!!source.assessment;$('#lessonDialog').dataset.scheduleId=scheduleId||source.scheduleId||'';$('#dialogTitle').textContent=`${source.className||'Новый урок'} · ${source.subject}`;$('#lessonDialog').showModal()}
async function saveLesson(){let id=$('#recordId').value, schedId=$('#lessonDialog').dataset.scheduleId;let r={id:id||uid(),scheduleId:schedId||'',date:$('#formDate').value,time:$('#formTime').value,className:$('#formClass').value.trim(),subject:$('#formSubject').value,status:$('#formStatus').value,topic:$('#formTopic').value.trim(),homework:$('#formHomework').value.trim(),notes:$('#formNotes').value.trim(),assessment:$('#formAssessment').checked};try{await saveLessonCloud(r);let idx=records.findIndex(x=>x.id===r.id);if(idx>=0)records[idx]=r;else records.push(r);localSave();$('#lessonDialog').close();selectedDate=parseDate(r.date);toast('Отчёт сохранён');render()}catch(e){console.error(e);toast('Не удалось сохранить запись')}}
async function quickStatus(scheduleId,status){let d=iso(selectedDate),s=schedule.find(x=>x.id===scheduleId),r=getRecord(d,s);if(!r){r={id:uid(),scheduleId,date:d,time:s.time,className:s.className,subject:s.subject,topic:'',homework:'',notes:'',assessment:false};}r.status=status;try{await saveLessonCloud(r);let idx=records.findIndex(x=>x.id===r.id);if(idx>=0)records[idx]=r;else records.push(r);localSave();toast('Статус обновлён');render()}catch(e){console.error(e);toast('Не удалось обновить статус')}}
function openSchedule(id){let s=id?schedule.find(x=>x.id===id):{id:'',day:1,time:'',className:'',subject:'Информатика'};$('#scheduleId').value=s.id;$('#scheduleDay').value=s.day;$('#scheduleTime').value=s.time;$('#scheduleClass').value=s.className;$('#scheduleSubject').value=s.subject;$('#deleteScheduleBtn').style.visibility=id?'visible':'hidden';$('#scheduleDialogTitle').textContent=id?'Редактировать урок':'Добавить урок';$('#scheduleDialog').showModal()}
async function saveSchedule(){let id=$('#scheduleId').value,s={id:id||`s${Date.now()}`,day:+$('#scheduleDay').value,time:$('#scheduleTime').value,className:$('#scheduleClass').value.trim(),subject:$('#scheduleSubject').value};try{await saveScheduleCloud(s);let i=schedule.findIndex(x=>x.id===id);if(i>=0)schedule[i]=s;else schedule.push(s);localSave();$('#scheduleDialog').close();toast('Расписание обновлено');render()}catch(e){console.error(e);toast('Не удалось сохранить расписание')}}
function exportCSV(){let rows=[['Дата','Время','Класс','Предмет','Статус','Тема','Домашнее задание','Заметки','Оценивание']];records.sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)).forEach(r=>rows.push([r.date,r.time,r.className,r.subject,statusName(r.status),r.topic,r.homework,r.notes,r.assessment?'Да':'Нет']));let csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(';')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='журнал-уроков.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV-файл подготовлен')}
$('.main-nav').addEventListener('click',e=>{let b=e.target.closest('[data-view]');if(b){view=b.dataset.view;render()}});$('#datePicker').onchange=e=>{selectedDate=parseDate(e.target.value);render()};$('#prevDay').onclick=()=>{selectedDate.setDate(selectedDate.getDate()-1);render()};$('#nextDay').onclick=()=>{selectedDate.setDate(selectedDate.getDate()+1);render()};$('#todayBtn').onclick=()=>{selectedDate=new Date();render()};['searchInput','classFilter','subjectFilter','statusFilter'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',renderJournal));$('#lessonsList').addEventListener('click',e=>{let b=e.target.closest('[data-edit]');if(b)openLesson(b.dataset.edit,b.dataset.schedule)});$('#lessonsList').addEventListener('change',e=>{if(e.target.matches('.status-select'))quickStatus(e.target.dataset.schedule,e.target.value)});$('#addBtn').onclick=()=>openLesson();$('#lessonForm').onsubmit=e=>{e.preventDefault();saveLesson()};$$('.close-dialog').forEach(b=>b.onclick=()=>$('#lessonDialog').close());$('#weekGrid').onclick=e=>{let x=e.target.closest('[data-open-date]');if(x){selectedDate=parseDate(x.dataset.openDate);openLesson('',x.dataset.openSchedule,x.dataset.openDate)}};$('#prevWeek').onclick=()=>{selectedDate.setDate(selectedDate.getDate()-7);render()};$('#nextWeek').onclick=()=>{selectedDate.setDate(selectedDate.getDate()+7);render()};$('#weekToday').onclick=()=>{selectedDate=new Date();render()};$('#calendar').onclick=e=>{let b=e.target.closest('[data-cal-date]');if(b){selectedDate=parseDate(b.dataset.calDate);view='journal';render()}};$('#prevMonth').onclick=()=>{selectedDate=new Date(selectedDate.getFullYear(),selectedDate.getMonth()-1,1);render()};$('#nextMonth').onclick=()=>{selectedDate=new Date(selectedDate.getFullYear(),selectedDate.getMonth()+1,1);render()};$('#monthToday').onclick=()=>{selectedDate=new Date();render()};$('#scheduleGrid').onclick=e=>{let b=e.target.closest('[data-schedule-edit]');if(b)openSchedule(b.dataset.scheduleEdit)};$('#scheduleAddBtn').onclick=()=>openSchedule();$('#scheduleForm').onsubmit=e=>{e.preventDefault();saveSchedule()};$$('.close-schedule').forEach(b=>b.onclick=()=>$('#scheduleDialog').close());$('#deleteScheduleBtn').onclick=async()=>{let id=$('#scheduleId').value;if(!id)return;try{await deleteScheduleCloud(id);schedule=schedule.filter(s=>s.id!==id);localSave();$('#scheduleDialog').close();toast('Урок удалён из расписания');render()}catch(e){console.error(e);toast('Не удалось удалить урок')}};$('#exportBtn').onclick=exportCSV;$('#printBtn').onclick=()=>window.print();
async function startApp(){const {data:{session}}=await supabaseClient.auth.getSession();currentUser=session?.user||null;if(!currentUser){$('#authScreen').classList.add('visible');return;}$('#authScreen').classList.remove('visible');try{await loadCloudData();render()}catch(e){console.error(e);toast('Не удалось загрузить данные')}}
$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value;$('#authMessage').textContent='Выполняется вход…';const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){$('#authMessage').textContent='Ошибка входа: '+error.message;return;}await startApp()};
$('#signupBtn').onclick=async()=>{const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||password.length<6){$('#authMessage').textContent='Укажите email и пароль не короче 6 символов.';return;}$('#authMessage').textContent='Создаём аккаунт…';const {data,error}=await supabaseClient.auth.signUp({email,password});if(error){$('#authMessage').textContent='Ошибка: '+error.message;return;}if(data.session) await startApp(); else $('#authMessage').textContent='Аккаунт создан. Проверьте почту и подтвердите email, затем войдите.'};
$('#logoutBtn').onclick=async()=>{await supabaseClient.auth.signOut();location.reload()};
supabaseClient.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){currentUser=null;$('#authScreen').classList.add('visible')}});startApp();
